### ISSUE TITLE
Peer to Peer Review

### ISSUE THREAD

**Issue by mnaibei** [mahabubx7/todo-list#3]
Hello Mahabub, great job on creating this project.
I just have one point to note, since you have not deployed the project please consider removing **Deployment** from your README.md.

**Comment by mahabubx7** [comment]
@mnaibei Thank you :handshake: .
I'm going to remove that asap.

**Comment by mahabubx7** [comment]
:heavy_check_mark: It is accomplished.
https://github.com/mahabubx7/todo-list/blob/bb5fd77134abedbd254d4714952e560c8ca7f450/README.md?plain=1#L128-L130
